parserOptions:
  ecmaVersion: 8

extends:
  - standard
  - plugin:react/recommended
  - plugin:vue/recommended

rules:
  react/react-in-jsx-scope: 0
  react/no-unknown-property: 0
  react/display-name: 0
  react/jsx-key: 0
